from .department.department_serializer import DepartmentSerializer
from .designation.designation_serializer import DesignationSerializer
from .user.user_serializer import UserSerializer
from .employee.employee_serializer import EmployeeSerializer